### PR TITLE
update CI to rely on auto-installation and Github Actions

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
@Non-Contradiction I'll let this PR be the final test before tagging. Let me know when I should re-run it.

@christopher-dG let me know if anything looks fishy in the CI file here. Otherwise, this seems to be the finish line 🎉

### CODE REVIEW

**Comment by christopher-dG** [comment]
This looks like a syntax error, needs parens:
 
https://github.com/SciML/diffeqr/blob/bd878d3bf267e97f230fe5fdc7f1ca4e72a2e3d3/R/diffeqr.R#L21

**Comment by ChrisRackauckas** [comment]
Thanks. I think https://github.com/Non-Contradiction/JuliaCall/pull/151 just handled it a bit nicer too.

**Comment by Non-Contradiction** [comment]
The new version of JuliaCall is on CRAN!

**Comment by ChrisRackauckas** [comment]
@Non-Contradiction it looks like packages might be installed to a wrong or different repository than what is checked?

**Comment by Non-Contradiction** [comment]
After reading the code in diffeqr and the test file, I find that with the new pkg_check argument, the julia differential equation package is not installed automatically? So there is actually no julia diffeq package on the CI system?

**Comment by ChrisRackauckas** [comment]
Oh the default on that was incorrect.

**Pull request merged**
